# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.encryptTab = QtWidgets.QWidget()
        self.encryptTab.setObjectName("encryptTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.encryptTab)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(9, -1, 9, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.LSB_pushButton = QtWidgets.QPushButton(self.encryptTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LSB_pushButton.sizePolicy().hasHeightForWidth())
        self.LSB_pushButton.setSizePolicy(sizePolicy)
        self.LSB_pushButton.setMinimumSize(QtCore.QSize(120, 30))
        self.LSB_pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.LSB_pushButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.LSB_pushButton.setBaseSize(QtCore.QSize(0, 0))
        self.LSB_pushButton.setObjectName("LSB_pushButton")
        self.verticalLayout.addWidget(self.LSB_pushButton, 0, QtCore.Qt.AlignHCenter)

        self.JsteG_pushButton = QtWidgets.QPushButton(self.encryptTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JsteG_pushButton.sizePolicy().hasHeightForWidth())
        self.JsteG_pushButton.setSizePolicy(sizePolicy)
        self.JsteG_pushButton.setMinimumSize(QtCore.QSize(120, 30))
        self.JsteG_pushButton.setObjectName("JsteG_pushButton")
        self.verticalLayout.addWidget(self.JsteG_pushButton, 0, QtCore.Qt.AlignHCenter)

        self.F3_pushButton = QtWidgets.QPushButton(self.encryptTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F3_pushButton.sizePolicy().hasHeightForWidth())
        self.F3_pushButton.setSizePolicy(sizePolicy)
        self.F3_pushButton.setMinimumSize(QtCore.QSize(120, 30))
        self.F3_pushButton.setObjectName("F3_pushButton")
        self.verticalLayout.addWidget(self.F3_pushButton, 0, QtCore.Qt.AlignHCenter)

        self.F5_pushButton = QtWidgets.QPushButton(self.encryptTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F5_pushButton.sizePolicy().hasHeightForWidth())
        self.F5_pushButton.setSizePolicy(sizePolicy)
        self.F5_pushButton.setMinimumSize(QtCore.QSize(120, 30))
        self.F5_pushButton.setObjectName("F5_pushButton")
        self.verticalLayout.addWidget(self.F5_pushButton, 0, QtCore.Qt.AlignHCenter)

        self.Ezsetgo_pushButton = QtWidgets.QPushButton(self.encryptTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ezsetgo_pushButton.sizePolicy().hasHeightForWidth())
        self.Ezsetgo_pushButton.setSizePolicy(sizePolicy)
        self.Ezsetgo_pushButton.setMinimumSize(QtCore.QSize(120, 30))
        self.Ezsetgo_pushButton.setObjectName("Ezsetgo_pushButton")
        self.verticalLayout.addWidget(self.Ezsetgo_pushButton, 0, QtCore.Qt.AlignHCenter)
        
        #
        self.imgfile_pushButton = QtWidgets.QPushButton(self.encryptTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgfile_pushButton.sizePolicy().hasHeightForWidth())
        self.imgfile_pushButton.setSizePolicy(sizePolicy)
        self.imgfile_pushButton.setMinimumSize(QtCore.QSize(120, 30))
        self.imgfile_pushButton.setObjectName("imgfile_pushButton")
        self.verticalLayout.addWidget(self.imgfile_pushButton, 0, QtCore.Qt.AlignHCenter)
        #
        self.watermark_pushButton = QtWidgets.QPushButton(self.encryptTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.watermark_pushButton.sizePolicy().hasHeightForWidth())
        self.watermark_pushButton.setSizePolicy(sizePolicy)
        self.watermark_pushButton.setMinimumSize(QtCore.QSize(120, 30))
        self.watermark_pushButton.setObjectName("watermark_pushButton")
        self.verticalLayout.addWidget(self.watermark_pushButton, 0, QtCore.Qt.AlignHCenter)

        self.tabWidget.addTab(self.encryptTab, "")
        self.decodeTab = QtWidgets.QWidget()
        self.decodeTab.setObjectName("decodeTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.decodeTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.pushButton = QtWidgets.QPushButton(self.decodeTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton.setObjectName("pushButton")        
        self.verticalLayout_2.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)

        self.pushButton_2 = QtWidgets.QPushButton(self.decodeTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_2.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignHCenter)

        self.pushButton_3 = QtWidgets.QPushButton(self.decodeTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignHCenter)

        self.pushButton_4 = QtWidgets.QPushButton(self.decodeTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4, 0, QtCore.Qt.AlignHCenter)

        self.pushButton_5 = QtWidgets.QPushButton(self.decodeTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignHCenter)

        self.pushButton_6 = QtWidgets.QPushButton(self.decodeTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6, 0, QtCore.Qt.AlignHCenter)
        #self.pushButton_7 = QtWidgets.QPushButton(self.decodeTab)
        #sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        #sizePolicy.setHorizontalStretch(0)
        #sizePolicy.setVerticalStretch(0)
        #sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        #self.pushButton_7.setSizePolicy(sizePolicy)
        #self.pushButton_7.setMinimumSize(QtCore.QSize(120, 30))
        #self.pushButton_7.setObjectName("pushButton_7")
        #self.verticalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.decodeTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8, 0, QtCore.Qt.AlignHCenter)

        self.pushButton_9 = QtWidgets.QPushButton(self.decodeTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_2.addWidget(self.pushButton_9, 0, QtCore.Qt.AlignHCenter)

        self.tabWidget.addTab(self.decodeTab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.label = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("background-color: rgb(140, 210, 220);")
        #self.label.setText("Image Show")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图像隐写"))
        self.LSB_pushButton.setText(_translate("MainWindow", "LSB隐写"))
        self.JsteG_pushButton.setText(_translate("MainWindow", "Jsteg隐写"))
        self.F3_pushButton.setText(_translate("MainWindow", "F3隐写"))
        self.F5_pushButton.setText(_translate("MainWindow", "F5隐写"))
        self.Ezsetgo_pushButton.setText(_translate("MainWindow", "Ezsetgo隐写"))
        self.watermark_pushButton.setText(_translate("MainWindow", "添加水印"))
        #
        self.imgfile_pushButton.setText(_translate("MainWindow", "文件隐藏"))
        #
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.encryptTab), _translate("MainWindow", "隐写加密"))
        self.pushButton.setText(_translate("MainWindow", "LSB隐写解析"))
        self.pushButton_2.setText(_translate("MainWindow", "Jsteg隐写解析"))
        self.pushButton_3.setText(_translate("MainWindow", "F3隐写解析"))
        self.pushButton_4.setText(_translate("MainWindow", "F5隐写解析"))
        self.pushButton_5.setText(_translate("MainWindow", "Ezsetgo隐写解析"))
        self.pushButton_6.setText(_translate("MainWindow", "提取水印"))
        #self.pushButton_7.setText(_translate("MainWindow", "隐写方式分析"))
        self.pushButton_8.setText(_translate("MainWindow", "关键字检索"))
        self.pushButton_9.setText(_translate("MainWindow", "隐藏文件提取"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.decodeTab), _translate("MainWindow", "隐写解析"))
    def show(self,filename):
        self.label.setPixmap(filename)
    def showGif(self,movie):
        movie.setScaledSize(QSize(self.label.width(), self.label.height()))
        movie.setCacheMode(QtGui.QMovie.CacheAll)
        movie.setSpeed(100) 
        self.label.setMovie(movie)
        movie.start() 


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

